[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.webp"
  [headers.values]
    Content-Type = "image/webp"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
